### ISSUE TITLE
Manually calculate CCN of Flag::getRectangle

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#12]
Calcuclated CNN: 20
Located at: Flag::getRectangle@1050-1104@./src/net/sf/freecol/client/gui/dialog/Flag.java

**Comment by shrew97** [comment]
![84984575_2984698684876582_7731651954182455296_n](https://user-images.githubusercontent.com/22689212/74539641-b2874e80-4f3e-11ea-9dbe-47590d6706a3.jpg)

Manually calculated CCN: 19

**Comment by johanmoritz** [comment]
Manually calculated CCN: 15 (not sure where we differ...)
[getRectangleCCN.pdf](https://github.com/johanmoritz/freecol/files/4208346/getRectangleCCN.pdf)

**Comment by shrew97** [comment]
@johanmoritz When calculating the Cyclomatic Complexity of a program with multiples exit points there is a different formula that one should use (according to the TA and wiki). Try using the other one as shown here https://en.wikipedia.org/wiki/Cyclomatic_complexity

"Cyclomatic complexity may be extended to a program with multiple exit points; in this case it is equal to

π − s + 2,
where π is the number of decision points in the program, and s is the number of exit points."

Might very well change your result

**Comment by johanmoritz** [comment]
50 - 39 + 2 = 13, it changes things but not to the better ^^

**Comment by shrew97** [comment]
Ah, we're gonna need a 3rd person to help us with this one then. @rbratfors @adbjo @Kappenn anyone up for the task?

**Comment by adbjo** [comment]
Code coverage too low, replaced with Player::readChild@4453-4526@./src/net/sf/freecol/common/model/Player.java

See #33
