### ISSUE TITLE
Manually calculate CCN of BuildQueuePanel::updateBuildingList

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#13]
Calculated CNN: 20
Located at: BuildQueuePanel::updateBuildingList@753-820@./src/net/sf/freecol/client/gui/panel/BuildQueuePanel.java

**Comment by Kappenn** [comment]
Calculated CNN 23
![86463872_1737953769673718_452253901580664832_n](https://user-images.githubusercontent.com/33659766/74544516-8b814a80-4f47-11ea-953b-4176b18099c5.jpg)

**Comment by johanmoritz** [comment]
Calculated CCN 13 (calculated it wrong in pdf)

[updateBuildingListCCN.pdf](https://github.com/johanmoritz/freecol/files/4208300/updateBuildingListCCN.pdf)

**Comment by johanmoritz** [comment]
Not sure why get such a different answer. Can you describe whats going on in your picture 6 nodes from the bottom? It looks to me like you have an inner for loop there, but I can't seem to find it in the code.

**Comment by Kappenn** [comment]
` if (up != null && !current.contains(up)
 && (colonyBuilding == null || colonyBuilding.getType() != up)) {
reasons.add(Messages.getName(up));
}`
I treat each && condition as a nestled if statement 
`if(condition)`
    `if (condition)`
Thats probably why it looks so confusing.

**Comment by johanmoritz** [comment]
Oh! should we do that? I thought the we should only check every branch, not substatements

**Comment by Kappenn** [comment]
Ah, I see what you mean, since they are of the same branch in that case, could be that.

**Comment by adbjo** [comment]
Code coverage too low, replace with Monarch::initializeCaches@303-347@./src/net/sf/freecol/common/model/Monarch.java

See #35
