### ISSUE TITLE
Implement branch coverage by manual instrumentation, InGameController::buildColony

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#14]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
InGameController::buildColony@2485-2550@./src/net/sf/freecol/client/control/InGameController.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #25.
