### ISSUE TITLE
Implement branch coverage by manual instrumentation, AbstractionOption::readOption

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#15]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
AbstractOption::readOption@209-278@./src/net/sf/freecol/common/option/AbstractOption.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 89,9% coverage according to OpenClover.

**Comment by shrew97** [comment]
Fixed in afa8e12
