### ISSUE TITLE
Implement branch coverage by manual instrumentation, MapViewer::displayUnit

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#16]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
MapViewer::displayUnit@1903-1962@./src/net/sf/freecol/client/gui/MapViewer.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #26.
