### ISSUE TITLE
Implement branch coverage by manual instrumentation, AbstractCanvasListener::scroll

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#17]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
AbstractCanvasListener::scroll@112-147@./src/net/sf/freecol/client/gui/AbstractCanvasListener.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #27.
