### ISSUE TITLE
Implement branch coverage by manual instrumentation, AIColony::updateTileImprovementPlans

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#18]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
AIColony::updateTileImprovementPlans@1241-1301@./src/net/sf/freecol/server/ai/AIColony.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 75,4% coverage according to OpenClover.

**Comment by johanmoritz** [comment]
Resolved by 5f43499.
