### ISSUE TITLE
Implement branch coverage by manual instrumentation, Flag::getRectangle

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#19]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
Flag::getRectangle@1050-1104@./src/net/sf/freecol/client/gui/dialog/Flag.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #28
