### ISSUE TITLE
Implement branch coverage by manual instrumentation,ProductionLabel::ProductionLabel

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#20]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
ProductionLabel::ProductionLabel@126-182@./src/net/sf/freecol/client/gui/label/ProductionLabel.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #29.
