### ISSUE TITLE
Implement branch coverage by manual instrumentation, ColonizationMapLoader::loadMap

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#21]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
ColonizationMapLoader::loadMap@152-201@./src/net/sf/freecol/server/generator/ColonizationMapLoader.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #30.
