### ISSUE TITLE
Implement branch coverage by manual instrumentation, BuildQueuePanel::updateBuildingList

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#22]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
BuildQueuePanel::updateBuildingList@753-820@./src/net/sf/freecol/client/gui/panel/BuildQueuePanel.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Has 0% coverage according to OpenClover.

**Comment by rbratfors** [comment]
Replaced with issue #31.
