### ISSUE TITLE
 Implement branch coverage by manual instrumentation, ModelMessage::getDefaultDisplay

### ISSUE THREAD

**Issue by rbratfors** [johanmoritz/freecol#25]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
ModelMessage::getDefaultDisplay@287-321@./src/net/sf/freecol/common/model/ModelMessage.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Solved in 8f07889e26d4533cea0d8c91aedadb5f062c602d
