### ISSUE TITLE
 Implement branch coverage by manual instrumentation, Monarch::actionIsValid

### ISSUE THREAD

**Issue by rbratfors** [johanmoritz/freecol#26]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
Monarch::actionIsValid@380-415@./src/net/sf/freecol/common/model/Monarch.java
See 3.5.1 in task pdf

**Comment by shrew97** [comment]
Fixed in 8212f5e8b79904c8975cd98d01c26a43b261564e and 661a98e
