### ISSUE TITLE
 Implement branch coverage by manual instrumentation, BaseCostDecider::getCost

### ISSUE THREAD

**Issue by rbratfors** [johanmoritz/freecol#27]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
BaseCostDecider::getCost@56-117@./src/net/sf/freecol/common/model/pathfinding/BaseCostDecider.java
See 3.5.1 in task pdf

**Comment by Kappenn** [comment]
π = 23
s = 6
M = 23 - 6 +2 = 19

**Comment by Kappenn** [comment]
Solved in: a71b2e0c50d970be8d21b2d34967b0c57ff4ad60
