### ISSUE TITLE
 Implement branch coverage by manual instrumentation, Map::findMapPath

### ISSUE THREAD

**Issue by rbratfors** [johanmoritz/freecol#30]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
Map::findMapPath@1220-1283@./src/net/sf/freecol/common/model/Map.java
See 3.5.1 in task pdf

**Comment by adbjo** [comment]
Solved in f14d04290f3392cfd2495103172a539ef595ef35 and a63d379a7d386352f3237a8d84ff4fa11c3ca181
