### ISSUE TITLE
 Implement branch coverage by manual instrumentation, Monarch::initializeCaches

### ISSUE THREAD

**Issue by rbratfors** [johanmoritz/freecol#31]
Implement branch coverage by manual instrumentation of the source code for ten functions,
Do this for:
Monarch::initializeCaches@303-347@./src/net/sf/freecol/common/model/Monarch.java
See 3.5.1 in task pdf

**Comment by Kappenn** [comment]
Solved in: 7499aa66ef5a62d6ffe39b93c440484e6b39dba6
