### ISSUE TITLE
Manually calculate CCN of Player::readChild

### ISSUE THREAD

**Issue by adbjo** [johanmoritz/freecol#33]
OpenClover CCN: 22
Located at: Player::readChild@4453-4526@./src/net/sf/freecol/common/model/Player.java

**Comment by shrew97** [comment]
Manually calculated CCN: 21* (misscounted the amount of nodes, there are 43 and not 42)

![86841982_730519724148022_3481035113251209216_n](https://user-images.githubusercontent.com/22689212/74660203-f758f280-5195-11ea-99d3-ef4f6780cde8.jpg)

**Comment by johanmoritz** [comment]
![readChildCCN.pdf](https://github.com/johanmoritz/freecol/files/4224266/readChildCCN.pdf)

CCN = 65 - 46 + 2 = 21

Seems like have the same solution ^^
