### ISSUE TITLE
Manually calculate CCN of Monarch::actionIsValid

### ISSUE THREAD

**Issue by adbjo** [johanmoritz/freecol#34]
OpenClover CCN: 19
Located at: Monarch::actionIsValid@380-415@./src/net/sf/freecol/common/model/Monarch.java

**Comment by rbratfors** [comment]
Calculated CC as 5 ![Image from iOS(3)](https://user-images.githubusercontent.com/16944544/74658809-55380b00-5193-11ea-8a63-0eb3140c31b7.jpg)

**Comment by shrew97** [comment]
Manually calculated CCN: 5

![86703622_510169419643477_175012401119232000_n](https://user-images.githubusercontent.com/22689212/74658831-5e28dc80-5193-11ea-81e3-b54ec8a8c267.jpg)
