### ISSUE TITLE
Manually calculate CCN of Monarch::initializeCaches

### ISSUE THREAD

**Issue by adbjo** [johanmoritz/freecol#35]
OpenClover CCN: 25
Located at: Monarch::initializeCaches@303-347@./src/net/sf/freecol/common/model/Monarch.java

**Comment by Kappenn** [comment]
EDIT: Calculated CNN: 52-32+2=22

![86713587_486162222027598_1623080557908852736_n](https://user-images.githubusercontent.com/33659766/74663232-a946ed80-519b-11ea-92c6-41e06308bfd9.jpg)

**Comment by johanmoritz** [comment]
[initializeCachesCCN.pdf](https://github.com/johanmoritz/freecol/files/4224089/initializeCachesCCN.pdf)

CCN = 45 - 33 + 2 = 14
Left branch = true
Right branch = false

Not sure what it means in your graph @Kappenn when you have edges going into edges, could you clarify?
Looks to me like you have extra nodes/edges, for example in the second for loop:
- You branch once on `if` and then once more on an empty node (the one between the two `if`). Where is the extra branching coming from?
- In your graph you can walk `if` (depth 1), `if` (depth 2), `else if` (depth 2), `else if` (depth 1), which (I think) shouldn't be able to happen. The last `else if` (depth 1) can not be run if the `if` (depth 1) before if was true.

**Comment by Kappenn** [comment]
The edges going into edges are counted as their own edges, just drew it that way for less cluttering. Every edge going into an edge that goes back to the for-loop is from a different if/if else statement.
The node is the && statment and the node between the two ifs is also an if, I just didn't write it out.
As for the second note. You are correct, I've missed that!

Hope this clarify it a bit for you!

**Comment by johanmoritz** [comment]
Right of course! I always forget about the compound statements.

**Comment by johanmoritz** [comment]
[initializeCachesCCN2.pdf](https://github.com/johanmoritz/freecol/files/4225348/initializeCachesCCN2.pdf)

Updated: CCN = 55 - 38 + 2 = 19
