### ISSUE TITLE
Manually calculate CCN of Map::searchMap

### ISSUE THREAD

**Issue by johanmoritz** [johanmoritz/freecol#5]
Calculated ccn: 82
Located at: Map::searchMap@1754-2059@./src/net/sf/freecol/common/model/Map.java

**Comment by adbjo** [comment]
I got 58 by manual calculation.

**Comment by Kappenn** [comment]
I got 77 by Manual calculation

**Comment by adbjo** [comment]
Discarded in favor of less complex functions.
