### ISSUE TITLE
Manually calculate CCN of Scope::equals

### ISSUE THREAD

**Issue by shrew97** [johanmoritz/freecol#53]
CCN: 18
Scope::equals@351-395@./src/net/sf/freecol/common/model/Scope.java

**Comment by shrew97** [comment]
17 comparisons
14 return statements
comparisons-return+2=17-14+2=5 CCN

**Comment by Kappenn** [comment]
Same result here as well
π = 17
s = 14
M = 17 - 14 +2 = 5
