### ISSUE TITLE
Manually calculate CCN of ServerRegion::requireFixedRegions

### ISSUE THREAD

**Issue by johanmoritz** [johanmoritz/freecol#7]
Calculated ccn: 53
ServerRegion::requireFixedRegions@247-498@./src/net/sf/freecol/server/model/ServerRegion.java

**Comment by adbjo** [comment]
Replaced ReportCompactColonyPanel::updateColony with ServerRegion::requireFixedRegion

**Comment by adbjo** [comment]
Discarded in favor of less complex functions.
