### ISSUE TITLE
Manually calculate CCN of BaseCostDecider::getCost

### ISSUE THREAD

**Issue by Kappenn** [johanmoritz/freecol#9]
Calculated CNN 19
Located at: AbstractCanvasListener::scroll@112-147@./src/net/sf/freecol/client/gui/AbstractCanvasListener.java

**Comment by Kappenn** [comment]
Calculated CNN 17
![86800382_572780666644969_2785793561453395968_n](https://user-images.githubusercontent.com/33659766/74544455-72789980-4f47-11ea-99ac-016db76b64e7.jpg)

EDIT: For the new function getCost
π = 23
s = 6
M = 23 - 6 +2 = 19

**Comment by rbratfors** [comment]
Calculated CC 17 
![Image from iOS(1)](https://user-images.githubusercontent.com/16944544/74545379-131b8900-4f49-11ea-9afe-2f28997db5ef.jpg)

**Comment by rbratfors** [comment]
We're doing this function instead:
BaseCostDecider::getCost@56-117@./src/net/sf/freecol/common/model/pathfinding/BaseCostDecider.java

**Comment by rbratfors** [comment]
Caclulcated CC as 19 ![Image from iOS(2)](https://user-images.githubusercontent.com/16944544/74657091-caa1dc80-518f-11ea-970c-344f94d742c0.jpg)
